const DEFAULT_ERROR_CODE = 'INTERNAL SERVER ERROR';
const DEFAULT_ERROR_MSG = 'Something went wrong';
const DEFAULT_STATUS_CODE = 500;

export default { DEFAULT_STATUS_CODE, DEFAULT_ERROR_CODE, DEFAULT_ERROR_MSG };
